services:
  takjil-app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: takjil-ramadhan
    env_file:
      - ./.env
    environment:
      - PORT=3001
      - NODE_ENV=production
      - DB_PATH=/app/database/takjil.db
    volumes:
      - takjil_database:/app/database
      - takjil_backups:/app/backups
    restart: unless-stopped
    networks:
      - homelab-net

    # OPTIONAL: kalau ingin debug dari host server:
    ports:
      - "0.0.0.0:8181:3001"

volumes:
  takjil_database:
  takjil_backups:

networks:
  homelab-net:
    external: true
    name: homelab-net
