services:
  takjil-app:
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    container_name: takjil-ramadhan
    ports:
      - "8181:3001"
    volumes:
      - takjil_database:/app/database
      - takjil_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3001
      - DB_PATH=/app/database/takjil.db
      - ADMIN_PASSWORD=takjil2026
      - JWT_SECRET=JkDWtIpyRYlAHB8vYCU6xI/+a8XlICpnKo0Bl0caRcA=
    restart: unless-stopped
    networks:
      - takjil-network

volumes:
  takjil_node_modules:
  takjil_database:

networks:
  takjil-network:
    driver: bridge